Repository delira-dev/delira, pull requests merged in 2019-10, with the labels that each got.

#222 sampler kwargs and trainer fix
  delira/data_loading/data_manager.py
  delira/training/base_trainer.py
Labels: bug

#219 Remove deprecations
  .travis.yml
  delira/data_loading/__init__.py
  delira/data_loading/dataset.py
  delira/data_loading/load_utils.py
  delira/data_loading/nii.py
  delira/utils/__init__.py
  delira/utils/context_managers.py
  delira/utils/imageops.py
  requirements/base.txt
Labels: ready for review

#223 Fix Type Checks
  delira/data_loading/data_manager.py
Labels: bug

#215 Register logger
  delira/training/base_trainer.py
  delira/training/callbacks/abstract_callback.py
  delira/training/callbacks/logging_callback.py
  delira/training/predictor.py
  tests/logging/test_logging_outside_trainer.py
Labels: ready for review

#224 Fix lookup of non existent keys
  delira/utils/config.py
  tests/utils/test_config.py
Labels: bug, ready for review
