Repository delira-dev/delira, pull requests merged in 2019-09, with the labels that each got.

#199 Move coverage to tests
  .travis.yml
Labels: ready for review

#205 Travis fix
  requirements/base.txt
Labels: bug, ready for review

#206 Remove trixi
  delira/training/__init__.py
  delira/training/backends/chainer/experiment.py
  delira/training/backends/sklearn/experiment.py
  delira/training/backends/tf_eager/experiment.py
  delira/training/backends/tf_graph/experiment.py
  delira/training/backends/torch/experiment.py
  delira/training/backends/torchscript/experiment.py
  delira/training/base_experiment.py
  delira/training/parameters.py
  delira/utils/__init__.py
  delira/utils/codecs.py
  delira/utils/config.py
  requirements/base.txt
  requirements/tensorflow.txt
  requirements/torch.txt
  setup.cfg
  tests/training/backends/test_chainer.py
  tests/training/backends/test_sklearn.py
  tests/training/backends/test_tf_eager.py
  tests/training/backends/test_tf_graph.py
  tests/training/backends/test_torch.py
  tests/training/backends/test_torchscript.py
  tests/training/backends/utils.py
  tests/training/test_parameters.py
  tests/utils/test_codecs.py
  tests/utils/test_config.py
  tests/utils/test_messenger.py
Labels: ready for review

#201 Add training callbacks
  delira/training/backends/chainer/trainer.py
  delira/training/backends/sklearn/trainer.py
  delira/training/backends/tf_eager/trainer.py
  delira/training/backends/tf_graph/trainer.py
  delira/training/backends/torch/trainer.py
  delira/training/base_trainer.py
  delira/training/callbacks/abstract_callback.py
  delira/utils/messenger.py
  tests/training/backends/utils.py
  tests/utils/test_messenger.py
Labels: ready for review

#172 New metric calculation
  delira/logging/base_logger.py
  delira/models/abstract_network.py
  delira/models/backends/chainer/abstract_network.py
  delira/models/backends/sklearn/abstract_network.py
  delira/models/backends/tf_eager/abstract_network.py
  delira/models/backends/tf_graph/abstract_network.py
  delira/models/backends/torch/abstract_network.py
  delira/models/backends/torchscript/abstract_network.py
  delira/training/backends/chainer/trainer.py
  delira/training/backends/sklearn/experiment.py
  delira/training/backends/sklearn/trainer.py
  delira/training/backends/tf_eager/trainer.py
  delira/training/backends/tf_graph/trainer.py
  delira/training/backends/torch/trainer.py
  delira/training/backends/torchscript/trainer.py
  delira/training/base_experiment.py
  delira/training/base_trainer.py
  delira/training/callbacks/__init__.py
  delira/training/callbacks/abstract_callback.py
  delira/training/callbacks/logging_callback.py
  delira/training/predictor.py
  delira/utils/dict_reductions.py
  delira/utils/messenger.py
  docs/_static/class_hierarchy/delira_coarse.png
  docs/_static/class_hierarchy/delira_fine.png
  tests/logging/test_logging_frequency.py
  tests/training/backends/test_chainer.py
  tests/training/backends/test_sklearn.py
  tests/training/backends/test_tf_eager.py
  tests/training/backends/test_tf_graph.py
  tests/training/backends/test_torch.py
  tests/training/backends/test_torchscript.py
  tests/training/backends/utils.py
  tests/utils/dict_reductions.py
  tests/utils/test_codecs.py
  tests/utils/test_messenger.py
Labels: new feature, ready for review

#207 Correct error when updating config
  delira/utils/config.py
  tests/utils/test_config.py
Labels: bug, ready for review
